// ハロプロ タイピングゲーム - メンバーデータ
// romaji はそのままタイピング目標文字列として使用する(大文字小文字は無視)

const GROUPS = [
  {
    id: "morning",
    name: "モーニング娘。'26",
    color: "#E5457D",
    image: "images/group_morning.webp",
    members: [
      { name: "野中美希", romaji: "nonakamiki", image: "images/morning_nonaka.webp" },
      { name: "小田さくら", romaji: "odasakura", image: "images/morning_oda.webp" },
      { name: "牧野真莉愛", romaji: "makinomaria", image: "images/morning_makino.webp" },
      { name: "岡村ほまれ", romaji: "okamurahomare", image: "images/morning_okamura.webp" },
      { name: "山﨑愛生", romaji: "yamazakimei", image: "images/morning_yamazaki.webp" },
      { name: "櫻井梨央", romaji: "sakurairio", image: "images/morning_sakurai.webp" },
      { name: "井上春華", romaji: "inoueharuka", image: "images/morning_inoue.webp" },
      { name: "弓桁朱琴", romaji: "yumigetaako", image: "images/morning_yumigeta.webp" },
      { name: "杉原明紗", romaji: "sugiharameisa", image: "images/morning_sugihara.webp" },
      { name: "安田美結", romaji: "yasudamiyu", image: "images/morning_yasuda.webp" },
      { name: "鈴木もあ", romaji: "suzukimoa", image: "images/morning_suzuki.webp" },
      { name: "石川華望", romaji: "isikawahanano", image: "images/morning_ishikawa.webp" },
    ],
  },
  {
    id: "ange",
    name: "アンジュルム",
    color: "#FF85AD",
    image: "images/group_ange.webp",
    members: [
      { name: "伊勢鈴蘭", romaji: "isereira", image: "images/ange_ise.webp" },
      { name: "為永幸音", romaji: "tamenagasionn", image: "images/ange_tamenaga.webp" },
      { name: "橋迫鈴", romaji: "hasisakorinn", image: "images/ange_hashisako.webp" },
      { name: "川名凜", romaji: "kawanarinn", image: "images/ange_kawana.webp" },
      { name: "松本わかな", romaji: "matumotowakana", image: "images/ange_matsumoto.webp" },
      { name: "平山遊季", romaji: "hirayamayuki", image: "images/ange_hirayama.webp" },
      { name: "下井谷幸穂", romaji: "simoitaniyukiho", image: "images/ange_shimoitani.webp" },
      { name: "後藤花", romaji: "gotouhana", image: "images/ange_goto.webp" },
      { name: "長野桃羽", romaji: "naganomomoha", image: "images/ange_nagano.webp" },
    ],
  },
  {
    id: "juice",
    name: "Juice=Juice",
    color: "#FF9900",
    image: "images/group_juice.webp",
    members: [
      { name: "段原瑠々", romaji: "dannbararuru", image: "images/juice_dambara.webp" },
      { name: "井上玲音", romaji: "inouerei", image: "images/juice_inoue.webp" },
      { name: "工藤由愛", romaji: "kudouyume", image: "images/juice_kudou.webp" },
      { name: "松永里愛", romaji: "matunagariai", image: "images/juice_matsunaga.webp" },
      { name: "有澤一華", romaji: "arisawaitika", image: "images/juice_arisawa.webp" },
      { name: "入江里咲", romaji: "irierisa", image: "images/juice_irie.webp" },
      { name: "江端妃咲", romaji: "ebatakisaki", image: "images/juice_ebata.webp" },
      { name: "石山咲良", romaji: "isiyamasakura", image: "images/juice_ishiyama.webp" },
      { name: "遠藤彩加里", romaji: "enndouakari", image: "images/juice_endo.webp" },
      { name: "川嶋美楓", romaji: "kawasimamihu", image: "images/juice_kawashima.webp" },
      { name: "林仁愛", romaji: "hayasiniina", image: "images/juice_hayashi.webp" },
    ],
  },
  {
    id: "tsubaki",
    name: "つばきファクトリー",
    color: "#787FDC",
    image: "images/group_tsubaki.webp",
    members: [
      { name: "谷本安美", romaji: "tanimotoami", image: "images/tsubaki_tanimoto.webp" },
      { name: "小野瑞歩", romaji: "onomizuho", image: "images/tsubaki_ono.webp" },
      { name: "小野田紗栞", romaji: "onodasaori", image: "images/tsubaki_onoda.webp" },
      { name: "秋山眞緒", romaji: "akiyamamao", image: "images/tsubaki_akiyama.webp" },
      { name: "河西結心", romaji: "kasaiyuumi", image: "images/tsubaki_kasai.webp" },
      { name: "福田真琳", romaji: "hukudamarinn", image: "images/tsubaki_fukuda.webp" },
      { name: "豫風瑠乃", romaji: "yohuuruno", image: "images/tsubaki_yofu.webp" },
      { name: "石井泉羽", romaji: "isiimihane", image: "images/tsubaki_ishii.webp" },
      { name: "村田結生", romaji: "muratayuu", image: "images/tsubaki_murata.webp" },
      { name: "土居楓奏", romaji: "doihuuka", image: "images/tsubaki_doi.webp" },
      { name: "西村乙輝", romaji: "nisimuraituki", image: "images/tsubaki_nishimura.webp" },
    ],
  },
  {
    id: "beyo",
    name: "BEYOOOOONDS",
    color: "#BA3CB8",
    image: "images/group_beyo.webp",
    members: [
      { name: "西田汐里", romaji: "nisidasiori", image: "images/beyo_nishida.webp" },
      { name: "江口紗耶", romaji: "egutisaya", image: "images/beyo_eguchi.webp" },
      { name: "高瀬くるみ", romaji: "takasekurumi", image: "images/beyo_takase.webp" },
      { name: "前田こころ", romaji: "maedakokoro", image: "images/beyo_maeda.webp" },
      { name: "岡村美波", romaji: "okamuraminami", image: "images/beyo_okamura.webp" },
      { name: "清野桃々姫", romaji: "kiyonomomohime", image: "images/beyo_kiyono.webp" },
      { name: "平井美葉", romaji: "hiraimiyo", image: "images/beyo_hirai.webp" },
      { name: "小林萌花", romaji: "kobayasihonoka", image: "images/beyo_kobayashi.webp" },
      { name: "里吉うたの", romaji: "satoyosiutano", image: "images/beyo_satoyoshi.webp" },
      { name: "小島はな", romaji: "kojimahana", image: "images/beyo_kojima.webp" },
      { name: "大坪茉乃", romaji: "ootubomano", image: "images/beyo_otsubo.webp" },
      { name: "杉山結菜", romaji: "sugiyamayuna", image: "images/beyo_sugiyama.webp" },
    ],
  },
  {
    id: "ocha",
    name: "OCHA NORMA",
    color: "#41B06C",
    image: "images/group_ocha.webp",
    members: [
      { name: "斉藤円香", romaji: "saitoumadoka", image: "images/ocha_saito.webp" },
      { name: "広本瑠璃", romaji: "hiromotoruri", image: "images/ocha_hiromoto.webp" },
      { name: "米村姫良々", romaji: "yonemurakirara", image: "images/ocha_yonemura.webp" },
      { name: "窪田七海", romaji: "kubotananami", image: "images/ocha_kubota.webp" },
      { name: "中山夏月姫", romaji: "nakayamanatume", image: "images/ocha_nakayama.webp" },
      { name: "西﨑美空", romaji: "nisizakimiku", image: "images/ocha_nishizaki.webp" },
      { name: "北原もも", romaji: "kitaharamomo", image: "images/ocha_kitahara.webp" },
      { name: "筒井澪心", romaji: "tutuiroko", image: "images/ocha_tsutsui.webp" },
    ],
  },
  {
    id: "rosy",
    name: "ロージークロニクル",
    color: "#BF3B3B",
    image: "images/group_rosy.webp",
    members: [
      { name: "橋田歩果", romaji: "hasidahonoka", image: "images/rosy_hashida.webp" },
      { name: "吉田姫杷", romaji: "yosidahinoha", image: "images/rosy_yoshida.webp" },
      { name: "小野田華凜", romaji: "onodakarinn", image: "images/rosy_onoda.webp" },
      { name: "村越彩菜", romaji: "murakosiayana", image: "images/rosy_murakoshi.webp" },
      { name: "植村葉純", romaji: "uemurahasumi", image: "images/rosy_uemura.webp" },
      { name: "松原ユリヤ", romaji: "matubarayuriya", image: "images/rosy_matsubara.webp" },
      { name: "島川波菜", romaji: "simakawahana", image: "images/rosy_shimakawa.webp" },
      { name: "上村麗菜", romaji: "kamimurarena", image: "images/rosy_kamimuara.webp" },
      { name: "相馬優芽", romaji: "soumayume", image: "images/rosy_soma.webp" },
    ],
  },
];
